version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'tailwindcss'
        versions: ['>=4.0.0']
      - dependency-name: 'eslint'
        versions: ['>=9.0.0']
      - dependency-name: 'tailwind-variants'
        versions: ['>=1.0.0']
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 25
    schedule:
      interval: 'daily'
