version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'tailwindcss'
        # For graphql-request, ignore all Dependabot updates for version 6 and 7
        versions: ['4.x']
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 25
    schedule:
      interval: 'daily'
