# See: https://www.datocms.com/blog/offer-responsive-progressive-lqip-images-in-2020
fragment responsiveImageFragment on ResponsiveImage {
  title
  src
  width
  height
  alt
  base64
  sizes
  bgColor
}
