fragment TextImageFragment on TextImageRecord {
  __typename
  id
  structuredText {
    value
    blocks {
      __typename
      ... on MainHeadingRecord {
        id
        title
        subtitle(markdown: true)
      }
    }
  }
  fadeInText
  image {
    responsiveImage(imgixParams: { fit: crop, auto: compress, fm: avif }) {
      ...responsiveImageFragment
    }
  }
  fadeInImage
  imageLocation
  imageStyle
  displayStyle
}
