fragment FeaturedFragment on FeaturedRecord {
  __typename
  id
  posts {
    id
    title
    slug
    coverImage {
      responsiveImage(
        imgixParams: { fit: crop, w: 608, h: 264, auto: format }
      ) {
        ...responsiveImageFragment
      }
    }
  }
}
