fragment FeaturedFragment on FeaturedRecord {
  __typename
  fadeIn
  fadeInDelay
  id
  posts {
    id
    title
    slug
    coverImage {
      mobile390: responsiveImage(
        imgixParams: { fit: crop, auto: format, w: 356, h: 178 }
      ) {
        src
        srcSet
        width
        height
        sizes
      }
      mobile430: responsiveImage(
        imgixParams: { fit: crop, auto: format, w: 396, h: 198 }
      ) {
        src
        srcSet
        width
        height
        sizes
      }
      tablet: responsiveImage(
        imgixParams: { fit: crop, auto: format, w: 217, h: 95 }
      ) {
        src
        srcSet
        width
        height
        sizes
      }
      desktop: responsiveImage(
        imgixParams: { fit: crop, auto: format, w: 313, h: 136 }
      ) {
        src
        srcSet
        width
        height
        sizes
      }
    }
  }
}
