fragment TextFragment on TextRecord {
  __typename
  id
  fadeIn
  centerText
  structuredText {
    value
    blocks {
      ... on ImageRecord {
        id
        __typename
        image {
          responsiveImage(
            imgixParams: {
              fit: max
              w: 800
              h: 800
              auto: compress
              q: 60
              fm: avif
            }
          ) {
            ...responsiveImageFragment
          }
        }
      }
      ... on MainHeadingRecord {
        ...MainHeadingFragment
      }
    }
  }
}
