fragment TextImageFragment on TextImageRecord {
  __typename
  id
  structuredText {
    value
    blocks {
      __typename
      ... on MainHeadingRecord {
        ...MainHeadingFragment
      }
    }
  }
  fadeInText
  fadeInTextDelay
  image {
    responsiveImage(
      imgixParams: { fit: max, w: 800, h: 800, auto: format, q: 60 }
    ) {
      ...responsiveImageFragment
    }
  }
  fadeInImage
  fadeInImageDelay
  imageLocation
  imageStyle
  displayStyle
}
