query HomePage {
  site: _site {
    favicon: faviconMetaTags {
      ...metaTagsFragment
    }
  }
  page(filter: { slug: { eq: "" } }) {
    seo: _seoMetaTags {
      ...metaTagsFragment
    }
    id
    name
    slug
    content {
      ... on ImageRecord {
        ...ImageFragment
      }
      ... on TextRecord {
        ...TextFragment
      }
      ... on TextImageRecord {
        ...TextImageFragment
      }
      ... on FeaturedRecord {
        ...FeaturedFragment
      }
      ... on BlogRecord {
        ...BlogFragment
      }
      ... on CardRecord {
        ...CardFragment
      }
    }
  }
  allPages {
    id
    name
    slug
  }
  allPosts(orderBy: date_DESC) {
    id
    slug
    title
    date
    excerpt
    coverImage {
      responsiveImage(
        imgixParams: { fit: crop, w: 410, h: 178, auto: format }
      ) {
        ...responsiveImageFragment
      }
    }
  }
}
