query HomePage {
  site: _site {
    favicon: faviconMetaTags {
      ...metaTagsFragment
    }
  }
  page(filter: { slug: { eq: "" } }) {
    seo: _seoMetaTags {
      ...metaTagsFragment
    }
    id
    name
    slug
    content {
      ... on ImageRecord {
        __typename
        id
        image {
          responsiveImage(
            imgixParams: { fit: crop, w: 288, h: 288, auto: format }
          ) {
            ...responsiveImageFragment
          }
        }
      }
      ... on TextRecord {
        __typename
        id
        structuredText {
          value
          blocks {
            __typename
            ... on MainHeadingRecord {
              id
              title
              subtitle(markdown: true)
            }
          }
        }
      }
      ... on TextImageRecord {
        __typename
        id
        structuredText {
          value
          blocks {
            __typename
            ... on MainHeadingRecord {
              id
              title
              subtitle(markdown: true)
            }
          }
        }
        imageLocation
        imageStyle
        image {
          responsiveImage(
            imgixParams: { fit: crop, w: 288, h: 288, auto: format }
          ) {
            ...responsiveImageFragment
          }
        }
      }
      ... on FeaturedRecord {
        __typename
        id
        posts {
          id
          title
          slug
        }
      }
      ... on BlogRecord {
        __typename
        id
        imageBoolean
      }
      ... on GridRecord {
        __typename
        id
        title
        mobileColumns
        tabletColumns
        desktopColumns
        gap
        height
        sections {
          ... on GridImageRecord {
            __typename
            id
            mobilePosition
            tabletPosition
            desktopPosition
            image {
              responsiveImage(
                imgixParams: {
                  fit: crop
                  crop: focalpoint
                  ar: "1:1"
                  minH: 384
                  auto: format
                }
              ) {
                ...responsiveImageFragment
              }
            }
          }
          ... on GridTextRecord {
            __typename
            id
            mobilePosition
            tabletPosition
            desktopPosition
            structuredText {
              value
            }
          }
        }
      }
    }
  }
  allPages {
    id
    name
    slug
  }
  allPosts {
    id
    slug
    title
    date
    excerpt
    coverImage {
      responsiveImage(
        imgixParams: { fit: crop, w: 410, h: 178, auto: format }
      ) {
        ...responsiveImageFragment
      }
    }
  }
}
