query PostBySlug($slug: String) {
  site: _site {
    favicon: faviconMetaTags {
      ...metaTagsFragment
    }
  }
  post(filter: { slug: { eq: $slug } }) {
    seo: _seoMetaTags {
      ...metaTagsFragment
    }
    id
    title
    slug
    date
    excerpt
    author {
      name
      picture {
        responsiveImage(
          imgixParams: {
            fit: crop
            w: 48
            h: 48
            auto: format
            mask: "ellipse"
          }
        ) {
          ...responsiveImageFragment
        }
      }
    }
    category {
      name
      slug
    }
    coverImage {
      mobile390: responsiveImage(
        imgixParams: { fit: crop, auto: format, w: 356, h: 178 }
      ) {
        ...responsiveImageFragment
      }
      mobile430: responsiveImage(
        imgixParams: { fit: crop, auto: format, w: 396, h: 198 }
      ) {
        ...responsiveImageFragment
      }
      tablet: responsiveImage(
        imgixParams: { fit: crop, auto: format, w: 486, h: 243 }
      ) {
        ...responsiveImageFragment
      }
      desktop: responsiveImage(
        imgixParams: { fit: crop, auto: format, w: 678, h: 339 }
      ) {
        ...responsiveImageFragment
      }
    }
    section {
      ...SectionFragment
    }
  }
}
