query PostBySlug($slug: String) {
  site: _site {
    favicon: faviconMetaTags {
      ...metaTagsFragment
    }
  }
  post(filter: { slug: { eq: $slug } }) {
    seo: _seoMetaTags {
      ...metaTagsFragment
    }
    id
    title
    slug
    date
    excerpt
    author {
      name
      picture {
        responsiveImage(
          imgixParams: {
            fit: crop
            w: 48
            h: 48
            auto: compress
            fm: avif
            mask: "ellipse"
          }
        ) {
          ...responsiveImageFragment
        }
      }
    }
    category {
      name
      slug
    }
    coverImage {
      responsiveImage(
        imgixParams: { fit: max, w: 2000, h: 1000, auto: compress, fm: avif }
      ) {
        ...responsiveImageFragment
      }
    }
    content {
      value
      blocks {
        ... on ImageRecord {
          id
          __typename
          image {
            responsiveImage(
              imgixParams: {
                fit: max
                w: 800
                h: 800
                auto: compress
                q: 60
                fm: avif
              }
            ) {
              ...responsiveImageFragment
            }
          }
        }
        ... on MainHeadingRecord {
          id
          __typename
          title
          subtitle
        }
      }
    }
  }
}
