fragment SectionFragment on SectionRecord {
  id
  name
  description {
    value
    blocks {
      ... on ImageRecord {
        ...ImageFragment
      }
      ... on MainHeadingRecord {
        ...MainHeadingFragment
      }
      ... on TextImageRecord {
        ...TextImageFragment
      }
      ... on VideoRecord {
        ...VideoFragment
      }
      ... on ColumnRecord {
        ...ColumnFragment
      }
    }
  }
  section {
    id
    name
    description {
      value
      blocks {
        ... on ImageRecord {
          id
          __typename
          image {
            responsiveImage(
              imgixParams: { fit: max, w: 800, h: 800, auto: format, q: 60 }
            ) {
              ...responsiveImageFragment
            }
          }
        }
        ... on MainHeadingRecord {
          id
          __typename
          title
          subtitle
        }
      }
    }
    section {
      id
      name
      description {
        value
      }
    }
  }
}
